import {readFile,writeFile,mkdir,rm,cp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {esc as e,topicKey,topicSlug,published,minutes,headings,validate} from './lib.mjs';
process.chdir(fileURLToPath(new URL('.',import.meta.url)));
const review=process.argv.includes('--review');
const site=JSON.parse(await readFile('content/site.json','utf8'));
if(!review&&(!site.confirmed||!site.author||!/^https:\/\//.test(site.url))) throw Error('正式构建需要确认 site.json 中的名称、署名和 HTTPS 正式域名；本地审阅请运行 npm run build:review');
const all=JSON.parse(await readFile('content/posts.json','utf8')).concat(review?JSON.parse(await readFile('content/review.json','utf8')):[]); validate(all);
const posts=published(all,review), origin=review?'http://localhost:4322':new URL(site.url).origin;
const topics=new Map(); for(const p of posts) for(const t of new Set(p.topics.map(topicKey))) { if(!topics.has(t)) topics.set(t,{name:site.topicNames?.[t]||p.topics.find(v=>topicKey(v)===t),posts:[]}); topics.get(t).posts.push(p); }
const about=Boolean(site.author&&site.about&&site.links.some(l=>/^https:\/\//.test(l.url)));
const author=site.author||(review?'作者待确认':'');
const url=p=>`/posts/${p.slug}/`;
const tag=t=>`<a class="tag" href="/topics/${topicSlug(t)}/">${e(topics.get(topicKey(t))?.name||t)}</a>`;
const meta=p=>`<div class="meta"><time datetime="${p.date}">${p.date.replaceAll('-','.')}</time><span>${minutes(p)} 分钟阅读</span>${[...new Set(p.topics.map(topicKey))].map(tag).join('')}</div>`;
const rows=(ps,level=3)=>ps.map(p=>`<article class="post-row"><div><h${level}><a href="${url(p)}">${e(p.title)}</a></h${level}><p class="summary">${e(p.summary)}</p>${meta(p)}</div><span class="row-arrow" aria-hidden="true">↗</span></article>`).join('');
const cat='<img class="cat" src="/assets/cat.svg" width="64" height="48" alt="" aria-hidden="true">';
const searchData=JSON.stringify(posts.map(p=>({title:p.title,summary:p.summary,topics:p.topics.map(t=>topics.get(topicKey(t)).name),url:url(p)}))).replaceAll('<','\\u003c');
const nav=(path)=>[['/','首页'],['/archive/','归档'],['/topics/','主题'],...(about?[['/about/','关于']]:[])].map(([u,n])=>`<a href="${u}" ${path===u||u==='/topics/'&&path.startsWith(u)?'aria-current="page"':''}>${n}</a>`).join('');
const routes=[];
function page(path,title,content,description=site.description,post=null) {
 const canonical=origin+path; routes.push(path);
 const structured={'@context':'https://schema.org','@type':post?'BlogPosting':'WebSite',name:title,url:canonical,...(post?{headline:post.title,datePublished:post.date,author:{'@type':'Person',name:post.author||author},image:origin+'/assets/share.png'}:{})};
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title===site.name?site.name:title+' · '+site.name)}</title><meta name="description" content="${e(description)}">${review?'<meta name="robots" content="noindex,nofollow">':''}<link rel="canonical" href="${e(canonical)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="${post?'article':'website'}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${origin}/assets/share.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/cat.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="${e(site.name)}" href="/rss.xml"><script>document.documentElement.classList.add('js');try{if(localStorage.getItem('theme')==='dark')document.documentElement.dataset.theme='dark'}catch{}</script><link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">${JSON.stringify(structured).replaceAll('<','\\u003c')}</script><script id="search-data" type="application/json">${searchData}</script><script src="/assets/app.js" defer></script></head><body><a class="skip" href="#main">跳到正文</a><header class="site-header wrap"><a class="brand" href="/">${e(site.name)}<span class="brand-en">PERSONAL<br>BLOG</span></a><nav class="desktop-nav" aria-label="主导航">${nav(path)}</nav><div class="tools"><button data-search class="js-only icon" aria-label="搜索文章">⌕</button><button data-theme class="js-only icon desktop-theme" aria-label="切换深色主题">◐</button><details class="mobile-menu"><summary aria-label="展开导航菜单">菜单</summary><nav aria-label="手机导航">${nav(path)}<button data-theme class="js-only">切换深浅主题</button><button class="js-only" data-close-menu>关闭菜单</button></nav></details></div></header>${review?'<div class="review wrap">设计审阅模式 · 包含明确标注的示意文章，不用于发布</div>':''}<main id="main" class="wrap">${content}</main><footer class="wrap"><div><a class="footer-name" href="/">${e(site.name)}</a><span>文字有处安放，日子慢慢生长。</span></div><div><span>${e(author)}</span><a href="/rss.xml">RSS 订阅 ↗</a>${site.links.filter(l=>/^https:\/\//.test(l.url)).map(l=>`<a href="${e(l.url)}" rel="me noreferrer">${e(l.label)} ↗</a>`).join('')}</div></footer><dialog aria-labelledby="search-title"><div class="dialog-head"><h2 id="search-title">寻找一段文字</h2><button data-close-search aria-label="关闭搜索">关闭 Esc</button></div><label for="query">搜索标题、摘要与主题</label><input id="query" type="search" placeholder="输入关键词，例如：hello" autocomplete="off"><div class="search-line"><p id="search-status" role="status">输入关键词，发现感兴趣的文章。</p><button id="clear-search">清空搜索</button></div><div id="results"></div></dialog><p class="toast" role="status" id="feedback"></p><a href="#main" class="back-top js-only" hidden>↑ 返回顶部</a></body></html>`;
}
await rm('dist',{recursive:true,force:true}); await mkdir('dist',{recursive:true}); await cp('assets','dist/assets',{recursive:true});
async function output(path,html){const target=`dist${path.endsWith('/')?path+'index.html':path}`;await mkdir(target.slice(0,target.lastIndexOf('/')),{recursive:true});await writeFile(target,html);}
const themeLinks=[...topics].map(([key,t])=>`<a class="topic-tile" href="/topics/${topicSlug(key)}/"><span>${e(t.name)}</span><span>${t.posts.length} 篇 <b aria-hidden="true">↗</b></span></a>`);
await output('/',page('/',site.name,`<section class="intro"><div class="eyebrow"><span></span> 一间有猫经过的数字书房</div><h1>${e(site.name)}<span class="title-accent">.</span></h1><p>${e(site.description)}</p><div class="intro-actions">${posts.length?'<a class="primary" href="#recent">阅读文章 <span aria-hidden="true">↓</span></a>':''}${about?'<a href="/about/">关于我 ↗</a>':''}<span class="margin-note">一些记录，一点好奇。</span></div><div class="cat-corner"><div class="cat-track">${cat}</div><button class="js-only cat-button" id="walk">让小猫散个步 <span aria-hidden="true">→</span></button><span class="cat-note">偶尔发呆，也挺好。</span></div></section><section id="recent"><div class="section-head"><h2>最近文章 <span>RECENT WRITING</span></h2><a href="/archive/">全部文章 ↗</a></div>${posts.length?rows(posts.slice(0,6)):'<p class="empty">第一篇文章，还在慢慢酝酿。</p>'}</section>${topics.size?`<section class="topics-home"><div class="section-head"><h2>按主题探索 <span>COLLECTIONS</span></h2><a href="/topics/">全部主题 ↗</a></div><div class="topic-grid">${themeLinks.slice(0,8).join('')}</div></section>`:''}`));
await output('/archive/',page('/archive/','文章归档',`<div class="page-title"><p class="eyebrow">THE ARCHIVE</p><h1>文章归档<span class="title-dot">.</span></h1><p>一页一页，留下思考的痕迹。共 ${posts.length} 篇文章。</p></div>${[...new Set(posts.map(p=>p.date.slice(0,4)))].map(y=>`<section><h2 class="year">${y}</h2>${rows(posts.filter(p=>p.date.startsWith(y)))}</section>`).join('')||'<p class="empty">第一篇文章，还在慢慢酝酿。</p>'}`));
await output('/topics/',page('/topics/','主题',`<div class="page-title"><p class="eyebrow">COLLECTIONS</p><h1>循着兴趣，慢慢读<span class="title-dot">.</span></h1><p>从一个小小的念头，走向更多可能。</p></div><div class="topic-grid">${themeLinks.join('')||'<p>文章发布后，主题会出现在这里。</p>'}</div>`));
for(const [key,t] of topics){const path=`/topics/${topicSlug(key)}/`;await output(path,page(path,t.name,`<div class="page-title"><a href="/topics/">← 全部主题</a><h1>${e(t.name)}</h1><p>共 ${t.posts.length} 篇文章</p></div>${rows(t.posts,2)}`));}
function renderBody(p,hs){let i=0;return p.body.map(b=>{if(/^h[23]$/.test(b.type)){const h=hs[i++];return `<${b.type} id="${e(h.id)}">${e(b.text)}<button class="js-only heading-copy" data-copy="${e(h.id)}" aria-label="复制章节链接：${e(b.text)}">#</button></${b.type}>`;}switch(b.type){case'p':return `<p>${e(b.text)}</p>`;case'quote':return `<blockquote><p>${e(b.text)}</p></blockquote>`;case'list':return `<ul>${b.items.map(s=>`<li>${e(s)}</li>`).join('')}</ul>`;case'code':return `<div class="code-wrap"><div class="code-bar"><span>CODE</span><button class="js-only" data-code>复制代码</button></div><pre tabindex="0" aria-label="代码，可横向滚动"><code>${e(b.text).replace(/\b(const|let|for|of|return|function|console)\b/g,'<span class="keyword">$1</span>')}</code></pre></div>`;case'table':return `<div class="table-scroll" tabindex="0" role="region" aria-label="表格，可横向滚动"><table><thead><tr>${b.headers.map(s=>`<th scope="col">${e(s)}</th>`).join('')}</tr></thead><tbody>${b.rows.map(row=>`<tr>${row.map(s=>`<td>${e(s)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;case'image':if(!b.src?.startsWith('/assets/')||!b.alt||!(b.width>0&&b.height>0))throw Error('图片需要本地资源、替代文字及尺寸');return `<figure><a href="${e(b.src)}"><img src="${e(b.src)}" alt="${e(b.alt)}" width="${b.width}" height="${b.height}" loading="lazy"></a>${b.caption?`<figcaption>${e(b.caption)}</figcaption>`:''}</figure>`;default:throw Error(`不支持的正文类型 ${b.type}`);}}).join('');}
for(const [i,p] of posts.entries()){const hs=headings(p.body);const toc=hs.map(h=>`<a class="${h.type}" href="#${e(h.id)}">${e(h.text)}</a>`).join('');const adjacent=[posts[i-1],posts[i+1]].filter(Boolean);const related=posts.filter(q=>q!==p&&!adjacent.includes(q)&&q.topics.some(t=>p.topics.map(topicKey).includes(topicKey(t)))).slice(0,3);await output(url(p),page(url(p),p.title,`<progress class="reading-progress js-only" value="0" max="1" aria-label="正文阅读进度"></progress><header class="article-head"><a href="/archive/">← 返回归档</a><h1>${e(p.title)}</h1><p>${e(p.summary)}</p>${meta(p)}${p.sample?'<p class="sample-label">示意文章 · 仅用于设计与功能审阅</p>':''}</header><div class="reading-layout ${hs.length<2?'no-toc':''}">${hs.length>=2?`<aside class="toc"><details><summary>文章目录</summary><nav aria-label="文章目录">${toc}</nav></details></aside>`:''}<div class="reading-column"><article class="prose" id="article-body">${renderBody(p,hs)}</article><div class="author-line"><span>${e(p.author||author)} · ${e(site.name)}</span><button class="js-only" data-copy="">复制链接 ↗</button>${cat}</div>${adjacent.length?`<nav class="adjacent" aria-label="相邻文章">${posts[i-1]?`<a href="${url(posts[i-1])}"><small>← 较新一篇</small>${e(posts[i-1].title)}</a>`:''}${posts[i+1]?`<a href="${url(posts[i+1])}"><small>较早一篇 →</small>${e(posts[i+1].title)}</a>`:''}</nav>`:''}${related.length?`<section><h2>也许还想读</h2>${rows(related)}</section>`:''}</div></div>`,p.summary,p));}
if(about)await output('/about/',page('/about/','关于',`<div class="page-title"><p class="eyebrow">ABOUT</p><h1>${e(site.author)}</h1></div><div class="prose"><p>${e(site.about)}</p>${site.links.filter(l=>/^https:\/\//.test(l.url)).map(l=>`<p><a href="${e(l.url)}" rel="me noreferrer">${e(l.label)} ↗</a></p>`).join('')}</div>`));
await output('/404.html',page('/404.html','404 · 页面不存在',`<section class="not-found"><p class="eyebrow">A LITTLE LOST</p><h1>404 · 页面不存在</h1><p>小猫也没有找到这一页。</p><div class="lost-cat">${cat}<span aria-hidden="true">← ? →</span></div><a class="primary" href="/">返回首页</a> <a href="/archive/">浏览归档 ↗</a></section>`));
await output('/rss.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${e(site.name)}</title><link>${e(origin)}</link><description>${e(site.description)}</description>${posts.map(p=>`<item><title>${e(p.title)}</title><link>${origin}${url(p)}</link><guid>${origin}${url(p)}</guid><pubDate>${new Date(p.date).toUTCString()}</pubDate><description>${e(p.summary)}</description></item>`).join('')}</channel></rss>`);
await output('/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.filter(r=>r!=='/404.html').map(r=>`<url><loc>${e(origin+r)}</loc></url>`).join('')}</urlset>`);
await output('/robots.txt',review?'User-agent: *\nDisallow: /\n':`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`${review?'审阅':'正式'}构建完成：${posts.length} 篇文章，${topics.size} 个主题。`);
