import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || '/tmp/codex-blog-check/node_modules/playwright/index.mjs');
const browser = await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/tmp/codex-blog-browsers/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:844}}); const results=[]; const failures=[];
const url='http://127.0.0.1:4323/garden/posts/reading-fixture/';
let scripts=0, mode='timeout', attributes={};
page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1')&&r.status()>=400) failures.push(r.url());});
await page.route('https://giscus.app/**',async route=> {
  const request=route.request().url();
  if(request.endsWith('client.js')) {
    scripts++;
    if(mode==='blocked') return route.abort();
    return route.fulfill({contentType:'text/javascript',body:`(()=>{const script=document.currentScript; window.__giscusAttrs={...script.dataset}; const wrap=document.createElement('div');wrap.className='giscus';const iframe=document.createElement('iframe');iframe.src='https://giscus.app/widget';wrap.append(iframe);script.after(wrap);})();`});
  }
  return route.fulfill({contentType:'text/html',body:'<!doctype html><html><body>模拟评论状态，不是真实讨论。</body></html>'});
});
await page.goto(url); await page.waitForTimeout(300);
assert.equal(scripts,0); results.push('阈值外没有第三方请求');
const root=page.locator('[data-giscus]');
const top=await root.evaluate(el=>el.getBoundingClientRect().top+scrollY);
await page.evaluate(y=>scrollTo(0,y-innerHeight-310),top); await page.waitForTimeout(700);
assert.equal(scripts,0);
await page.evaluate(y=>scrollTo(0,y-innerHeight-280),top); await page.waitForTimeout(800);
assert.equal(scripts,1); results.push('300px 阈值内单次注入');
attributes=await page.evaluate(()=>window.__giscusAttrs);
assert.equal(attributes.term,'post:reading-fixture'); assert.equal(attributes.mapping,'specific'); assert.equal(attributes.strict,'1'); assert.equal(attributes.theme,'light');
await page.screenshot({path:'evidence/comments-loading.png'});
await page.waitForTimeout(10200); assert.match(await page.locator('.comment-status').textContent(),/较慢/); results.push('10 秒超时');
await page.screenshot({path:'evidence/comments-timeout.png'});
await page.evaluate(()=>window.__oldFrame=document.querySelector('.giscus-mount iframe').contentWindow);
await page.locator('.comment-retry').click(); await page.waitForTimeout(400); assert.equal(scripts,2); assert.equal(await page.locator('.giscus-mount iframe').count(),1);
await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{origin:'https://giscus.app',source:window,data:{giscus:{resizeHeight:200}}})));
assert.match(await page.locator('.comment-status').textContent(),/正在加载/); results.push('拒绝错误 iframe 来源的消息');
await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{origin:'https://giscus.app',source:window.__oldFrame,data:{giscus:{resizeHeight:200}}})));
assert.match(await page.locator('.comment-status').textContent(),/正在加载/); results.push('迟到旧实例消息不能覆盖重试状态');
const frame=page.frames().find(f=>f.url().startsWith('https://giscus.app/widget'));
await frame.evaluate(()=>parent.postMessage({giscus:{resizeHeight:200}},'http://127.0.0.1:4323')); await page.waitForTimeout(200);
assert.equal(await page.locator('.comment-status').textContent(),''); results.push('对应 iframe 就绪后清除提示');
await page.screenshot({path:'evidence/comments-ready-mock.png'});
mode='blocked'; await page.goto(url); await root.scrollIntoViewIfNeeded(); await page.waitForTimeout(700);
assert.match(await page.locator('.comment-status').textContent(),/失败/); results.push('第三方被拦截仍可阅读与重试');
await page.screenshot({path:'evidence/comments-blocked.png'});
const links=await page.locator('a[href^="/"]').evaluateAll(els=>els.map(el=>el.getAttribute('href')));
assert.ok(links.every(h=>h.startsWith('/garden/'))); results.push('导航、Markdown 根路径链接均带 base');
assert.ok((await page.locator('link[rel=canonical]').getAttribute('href')).includes('/garden/posts/'));
const og=await page.locator('meta[property="og:image"]').getAttribute('content');assert.ok(og.startsWith('https://example.com/garden/og/'));
assert.equal((await page.request.get(og.replace('https://example.com','http://127.0.0.1:4323'))).status(),200); results.push('分享图绝对 URL 与 base 可访问');
mode='timeout';
const fallback=await browser.newPage();
await fallback.addInitScript(()=>{delete window.IntersectionObserver;});
await fallback.route('https://giscus.app/**',route=>route.abort());
await fallback.goto(url);
assert.equal(await fallback.locator('.comment-retry').textContent(),'加载评论');
assert.equal(await fallback.locator('.comment-retry').isVisible(),true); results.push('无 IntersectionObserver 的手动入口');
await page.addInitScript(()=>addEventListener('DOMContentLoaded',()=>document.querySelector('.article-body')?.remove()));
await page.setViewportSize({width:1440,height:1200}); const before=scripts;
await page.goto(url); await page.waitForTimeout(700); assert.equal(scripts,before+1); results.push('短文首次渲染立即进入加载阈值');
assert.deepEqual(failures,[]);
await writeFile('evidence/comments-results.json',JSON.stringify({results,attributes,limitations:'仅模拟第三方传输；真实 repo / 登录 / Discussions 映射尚未验收。'},null,2));
await browser.close(); console.log(results);
